### ISSUE TITLE
Parameterize Redis CLI wrapper methods to allow custom ports

### ISSUE THREAD

**Issue by voltbit** [PayU/redis-operator#67]
The port parameter must be optional.

https://github.com/PayU/redis-operator/blob/master/controllers/rediscli/redis_cli.go

**Comment by sheetalsingala** [comment]
Hi, Can I give this a try?
Is the custom port passed with a '-p' flag? 
The functions that need change are - 
- `ClusterCreate`
- `ClusterCheck`
- `AddFollower`
- `DelFollower`

**Comment by voltbit** [comment]
Hello, sure!
There are two types of commands:
1. commands use flags for host and port like so: `redis-cli -h 127.0.0.1 -p 7000` - these should have a documentation link in the code to the Redis docs like so: `// https://redis.io/commands/info`
2. commands using ip:port format `redis-cli --cluster add-node 127.0.0.1:7003 127.0.0.1:7000 --cluster-slave`

Usually the commands that have the `--cluster` flag will be of the 2nd kind and all others of the 1st kind. The list you mentioned is with commands of the 2nd kind.

We should be able to provide the port to all of them and is important to be optional.
I think it is best if all methods support receiving the port as part of the `nodeIP` parameter as string in the format ip:port and then try to parse it to get the ip and port. If there is no port in the address then the default "6379" should be used.

We dont have automatic testing for this part of the code, but to test your changes you can make a small `main()` program where you import the rediscli package and then call the commands.

**Comment by voltbit** [comment]
Even better than using "6379" as default, we could add a field on the RedisCLI struct that holds the value of the default port [1]. The constructor needs a port parameter as well [2]. The only places where the constructor is called is at [3] and in the testing framework at [4].

[1] https://github.com/PayU/redis-operator/blob/master/controllers/rediscli/redis_cli.go#L15
[2] https://github.com/PayU/redis-operator/blob/master/controllers/rediscli/redis_cli.go#L19
[3] https://github.com/PayU/redis-operator/blob/master/main.go#L64
[4] https://github.com/PayU/redis-operator/blob/master/test/framework/framework.go#L72

**Comment by shyimo** [comment]
Hi @sheetalsingala . if you need any help feel free to reach out!

**Comment by sheetalsingala** [comment]
> Even better than using "6379" as default, we could add a field on the RedisCLI struct that holds the value of the default port [1]. The constructor needs a port parameter as well [2]. The only places where the constructor is called is at [3] and in the testing framework at [4].
> 
> [1] https://github.com/PayU/redis-operator/blob/master/controllers/rediscli/redis_cli.go#L15
> [2] https://github.com/PayU/redis-operator/blob/master/controllers/rediscli/redis_cli.go#L19
> [3] https://github.com/PayU/redis-operator/blob/master/main.go#L64
> [4] https://github.com/PayU/redis-operator/blob/master/test/framework/framework.go#L72

Thank you for the information. In case of commands of type 1, a port parameter is not always required ?

**Comment by voltbit** [comment]
> Thank you for the information. In case of commands of type 1, a port parameter is not always required ?

@sheetalsingala Yes, in the 1st type the port is always optional, so the `-p` in the command can be omitted if the address parameter only has an IP and not a port.

So for example for 1st kind: https://github.com/PayU/redis-operator/blob/master/controllers/rediscli/redis_cli.go#L139

the users should be able to call it both ways:

`RedisCLI.ClusterInfo("10.0.0.0")`  -> `redis-cli -h 10.0.0.0 cluster info`
`RedisCLI.ClusterInfo("10.0.0.0:8888")` -> `redis-cli -h 10.0.0.0 -p 8888 cluster info`

And for 2nd kind: https://github.com/PayU/redis-operator/blob/master/controllers/rediscli/redis_cli.go#L129

`RedisCLI.DelNode("10.0.0.0", "RedisID")` -> `redis-cli --cluster del-node 10.0.0.0:6379 RedisID`
`RedisCLI.DelNode("10.0.0.0:8888", "RedisID")` -> `redis-cli --cluster del-node 10.0.0.0:8888 RedisID`
