### ISSUE TITLE
Support configuration changes via redis.conf

### ISSUE THREAD

**Issue by voltbit** [PayU/redis-operator#75]
Right now if someone needs a paticular thing configured for redis via redis.conf file it can only be done through a code change + image rebuild since we store the redis config in the code. We should add the possibility of changing the config at runtime.
Ideas:

- could provide a file path through a flag on the operator - to change the the config a manual rolling restart would be needed on the redis cluster
- could make the operator monitor changes to the ConfigMap and start a rolling restart of the redis nodes with the new config, the users would have to create/edit the configmap

**Comment by shyimo** [comment]
We need to discuss it further. support configuration change will be very helpful but we cannot support all configuration changes. currently, some of the configurations are there to support our architecture of the operator . we need to think of a way to pass only some of the configuration that we are willing to change and document that

**Comment by voltbit** [comment]
The point is to let users change the redis.conf without having to recompile and deploy the code.
We can make a list of supported configurations.

**Comment by voltbit** [comment]
I came across this doc from `kustomize` what describes how changes in a ConfigMap are handled for a deployment. So when a ConfigMap used by a pod is changed, the pod is recreated as well. It does this by creating a hash of the ConfigMap and storing it as an annotation in the pod template of the deployment:

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configGeneration.md

I think we can to the same with the operator - after we store the redis.conf in a ConfigMap, we hash the CM and add it to the pod template on the RedisCliuster object.
The operator will have to monitor the ConfigMap resource for changes the same way it does with pods and RDCs.
