### ISSUE TITLE
kubectl explain returns nothing for the RedisCluster resource

### ISSUE THREAD

**Issue by voltbit** [PayU/redis-operator#97]
Using `kubectl explain` does not work on the RedisCluster resource.

```
$ kubectl explain rdc

KIND:     RedisCluster
VERSION:  db.payu.com/v1

DESCRIPTION:
     <empty>
```

**Comment by DinaYakovlev** [comment]
works for me... 
![image](https://user-images.githubusercontent.com/24668683/137155483-6d070aea-b605-4b8f-bf8e-2df20470ca06.png)
